name: Build HTML
on: 
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month on the first day
permissions:
  contents: write
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build HTML
        run: |
          GDRIVE_AUTH=$(echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" | base64 --decode | jq)
                  
          # Define collections and output files
          COLLECTIONS=("${{ secrets.ZOTERO_COLLECTION_BOOK }}" "${{ secrets.ZOTERO_COLLECTION_RECONF }}" "${{ secrets.ZOTERO_COLLECTION_WRITING }}")
          OUTPUT_FILES=("book.html" "reconfiguration.html" "writing.html")
                  
          # Loop through all collections
          for i in {0..2}; do
            python3 list-zotero-collection.py --api-key ${{ secrets.ZOTERO_API_KEY }} --library-id ${{ secrets.ZOTERO_LIBRARY_ID }} --collection "${COLLECTIONS[$i]}" --output-format html --output-file "${OUTPUT_FILES[$i]}" --service-account-file "${GDRIVE_AUTH}"
          done
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit and push changes
        run: |
          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
          git config --global user.name "${{ steps.import-gpg.outputs.name }}"
          NOW=$(date)
          git add --all .
          git commit -S -m "Update ${NOW}" || echo "No changes to commit"
          git push